BUNDLE_NAME = K2ge3Preferences
K2ge3Preferences_FILES = K2ge3RootListController.m
K2ge3Preferences_FRAMEWORKS = UIKit Foundation
K2ge3Preferences_PRIVATE_FRAMEWORKS = Preferences
K2ge3Preferences_INSTALL_PATH = /Library/PreferenceBundles
K2ge3Preferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
